services:
  _defaults:
    public: false

  Gember\EventSourcing\EventStore\EventStore:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsEventStore
    arguments:
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_domain_event_envelope_factory'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_event_factory'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_event_store_repository'

  gember.event_sourcing.event_store.domain_event_envelope_factory:
    class: Gember\EventSourcing\EventStore\DomainEventEnvelopeFactory
    arguments:
      - '@gember.event_sourcing.resolver.domain_message.domain_tags.domain_tags_resolver'
      - '@gember.event_sourcing.util.generator.identity.identity_generator'
      - '@gember.event_sourcing.util.time.clock.clock'

  gember.event_sourcing.event_store.rdbms.rdbms_domain_event_envelope_factory:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsDomainEventEnvelopeFactory
    arguments:
      - '@gember.event_sourcing.util.serialization.serializer.serializer'
      - '@gember.event_sourcing.registry.event.event_registry'

  gember.event_sourcing.event_store.rdbms.rdbms_event_factory:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsEventFactory
    arguments:
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'
      - '@gember.event_sourcing.util.serialization.serializer.serializer'

  gember.event_sourcing.event_store.rdbms.rdbms_event_store_repository:
    class: Gember\RdbmsEventStoreDoctrineDbal\DoctrineDbalRdbmsEventStoreRepository
    arguments:
      - '@gember.doctrine.dbal.connection'
      - '@gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_table_schema'
      - '@gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_relation_table_schema'
      - '@gember.rdbms_event_store_doctrine_dbal.doctrine_dbal_rdbms_event_factory'

  gember.doctrine.dbal.connection: '@doctrine.dbal.default_connection'

  gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_table_schema:
    class: Gember\RdbmsEventStoreDoctrineDbal\TableSchema\EventStoreTableSchema
    factory: [
      Gember\RdbmsEventStoreDoctrineDbal\TableSchema\TableSchemaFactory,
      'createDefaultEventStore'
    ]

  gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_relation_table_schema:
    class: Gember\RdbmsEventStoreDoctrineDbal\TableSchema\EventStoreRelationTableSchema
    factory: [
      Gember\RdbmsEventStoreDoctrineDbal\TableSchema\TableSchemaFactory,
      'createDefaultEventStoreRelation'
    ]

  gember.rdbms_event_store_doctrine_dbal.doctrine_dbal_rdbms_event_factory:
    class: Gember\RdbmsEventStoreDoctrineDbal\DoctrineDbalRdbmsEventFactory

  gember.event_sourcing.registry.event.event_registry:
    class: Gember\EventSourcing\Registry\Event\Reflector\ReflectorEventRegistry
    arguments:
      - '@gember.event_sourcing.util.file.finder.finder'
      - '@gember.event_sourcing.util.file.reflector.reflector'
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'

  gember.event_sourcing.registry.event.cached.cached_event_registry_decorator:
    class: Gember\EventSourcing\Registry\Event\Cached\CachedEventRegistryDecorator
    #decorates: gember.event_sourcing.registry.event.event_registry
    arguments:
      - '@.inner'
      - '@gember.psr.simple_cache.cache_interface'

  gember.event_sourcing.registry.command_handler.command_handler_registry:
    class: Gember\EventSourcing\Registry\CommandHandler\Reflector\ReflectorCommandHandlerRegistry
    arguments:
      - '@gember.event_sourcing.util.file.finder.finder'
      - '@gember.event_sourcing.util.file.reflector.reflector'
      - '@gember.event_sourcing.resolver.use_case.command_handlers.command_handlers_resolver'

  gember.event_sourcing.registry.command_handler.cached.cached_command_handler_registry_decorator:
    class: Gember\EventSourcing\Registry\CommandHandler\Cached\CachedCommandHandlerRegistryDecorator
    #decorates: gember.event_sourcing.registry.command_handler.command_handler_registry
    arguments:
      - '@.inner'
      - '@gember.psr.simple_cache.cache_interface'
      - '@gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer'

  gember.event_sourcing.resolver.use_case.command_handlers.command_handlers_resolver:
    class: Gember\EventSourcing\Resolver\UseCase\CommandHandlers\Attribute\AttributeCommandHandlersResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  Gember\EventSourcing\UseCase\CommandHandler\UseCaseCommandHandler:
    class: Gember\EventSourcing\UseCase\CommandHandler\UseCaseCommandHandler
    arguments:
      - '@gember.event_sourcing.repository.use_case_repository'
      - '@gember.event_sourcing.registry.command_handler.command_handler_registry'
      - '@gember.event_sourcing.resolver.domain_message.domain_tags.domain_tags_resolver'

  gember.event_sourcing.repository.use_case_repository:
    class: Gember\EventSourcing\Repository\EventSourced\EventSourcedUseCaseRepository
    arguments:
      - '@Gember\EventSourcing\EventStore\EventStore'
      - '@gember.event_sourcing.event_store.domain_event_envelope_factory'
      - '@gember.event_sourcing.resolver.use_case.subscribed_events.subscribed_events_resolver'
      - '@gember.event_sourcing.util.messaging.message_bus.event_bus'

  Gember\EventSourcing\Repository\UseCaseRepository: '@gember.event_sourcing.repository.use_case_repository'

  gember.event_sourcing.resolver.use_case.domain_tag_properties.domain_tag_properties_resolver:
    class: Gember\EventSourcing\Resolver\UseCase\DomainTagProperties\Attribute\AttributeDomainTagsPropertiesResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.use_case.subscribed_events.subscribed_events_resolver:
    class: Gember\EventSourcing\Resolver\UseCase\SubscribedEvents\Attribute\AttributeSubscribedEventsResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.use_case.subscriber_method_for_event.subscriber_method_for_event_resolver:
    class: Gember\EventSourcing\Resolver\UseCase\SubscriberMethodForEvent\Attribute\AttributeSubscriberMethodForEventResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_message.domain_tags.domain_tags_resolver:
    class: Gember\EventSourcing\Resolver\DomainMessage\DomainTags\Stacked\StackedDomainTagsResolver
    arguments:
      - [
        '@gember.event_sourcing.resolver.domain_message.domain_tags.attribute.attribute_domain_tags_resolver',
        '@gember.event_sourcing.resolver.domain_message.domain_tags.interface.interface_domain_tags_resolver'
      ]

  gember.event_sourcing.resolver.domain_message.domain_tags.attribute.attribute_domain_tags_resolver:
    class: Gember\EventSourcing\Resolver\DomainMessage\DomainTags\Attribute\AttributeDomainTagsResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_message.domain_tags.interface.interface_domain_tags_resolver:
    class: Gember\EventSourcing\Resolver\DomainMessage\DomainTags\Interface\InterfaceDomainTagsResolver

  gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Stacked\StackedNormalizedEventNameResolver
    arguments:
      - [
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.attribute.attribute_normalized_event_name_resolver',
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.interface.interface_normalized_event_name_resolver',
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.class_name.class_name_normalized_event_name_resolver'
      ]

  gember.event_sourcing.resolver.domain_event.normalized_event_name.attribute.attribute_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Attribute\AttributeNormalizedEventNameResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_event.normalized_event_name.interface.interface_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Interface\InterfaceNormalizedEventNameResolver

  gember.event_sourcing.resolver.domain_event.normalized_event_name.class_name.class_name_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\ClassName\ClassNameNormalizedEventNameResolver
    arguments:
      - '@gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer'

  gember.event_sourcing.util.attribute.resolver.attribute_resolver:
    class: Gember\EventSourcing\Util\Attribute\Resolver\Reflector\ReflectorAttributeResolver

  gember.event_sourcing.util.resolver.cached.cached_attribute_resolver_decorator:
    class: Gember\EventSourcing\Util\Attribute\Resolver\Cached\CachedAttributeResolverDecorator
    #decorates: gember.event_sourcing.util.attribute.resolver.attribute_resolver
    arguments:
      - '@.inner'
      - '@gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer'
      - '@gember.psr.simple_cache.cache_interface'

  gember.psr.simple_cache.cache_interface: '@gember.symfony.component.cache.psr16_cache'

  gember.symfony.component.cache.psr16_cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@gember.psr.cache.cache_item_pool_interface'

  gember.psr.cache.cache_item_pool_interface: ~

  gember.event_sourcing.util.file.finder.finder:
    class: Gember\EventSourcing\Util\File\Finder\Native\NativeFinder

  gember.event_sourcing.util.file.reflector.reflector:
    class: Gember\EventSourcing\Util\File\Reflector\Native\NativeReflector

  gember.event_sourcing.util.generator.identity.identity_generator: '@gember.identity_generator_symfony.uuid.symfony_uuid_identity_generator'

  Gember\DependencyContracts\Util\Generator\Identity\IdentityGenerator: '@gember.event_sourcing.util.generator.identity.identity_generator'

  gember.identity_generator_symfony.uuid.symfony_uuid_identity_generator:
    class: Gember\IdentityGeneratorSymfony\Uuid\SymfonyUuidIdentityGenerator
    arguments:
      - '@Symfony\Component\Uid\Factory\UuidFactory'

  gember.identity_generator_symfony.ulid.symfony_ulid_identity_generator:
    class: Gember\IdentityGeneratorSymfony\Ulid\SymfonyUlidIdentityGenerator
    arguments:
      - '@Symfony\Component\Uid\Factory\UlidFactory'

  gember.event_sourcing.util.messaging.message_bus.event_bus:
    class: Gember\MessageBusSymfony\SymfonyEventBus
    arguments:
      - '@gember.symfony.component.messenger.message_bus.event_bus'

  gember.symfony.component.messenger.message_bus.event_bus: '@event.bus'

  gember.event_sourcing.util.serialization.serializer.serializer:
    class: Gember\EventSourcing\Util\Serialization\Serializer\Stacked\StackedSerializer
    arguments:
      - [
        '@gember.event_sourcing.util.serialization.serializer.serializable_domain_event.serializable_domain_event_serializer',
        '@gember.serializer_symfony.symfony_serializer'
      ]

  gember.event_sourcing.util.serialization.serializer.serializable_domain_event.serializable_domain_event_serializer:
    class: Gember\EventSourcing\Util\Serialization\Serializer\SerializableDomainEvent\SerializableDomainEventSerializer

  gember.serializer_symfony.symfony_serializer:
    class: Gember\SerializerSymfony\SymfonySerializer
    arguments:
      - '@gember.symfony.component.serializer.serializer_interface'

  gember.symfony.component.serializer.serializer_interface: '@serializer'

  gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer:
    class: Gember\EventSourcing\Util\String\FriendlyClassNamer\Native\NativeFriendlyClassNamer
    arguments:
      - '@gember.event_sourcing.util.string.inflector.inflector'

  gember.event_sourcing.util.string.inflector.inflector:
    class: Gember\EventSourcing\Util\String\Inflector\Native\NativeInflector

  gember.event_sourcing.util.time.clock.clock:
    class: Gember\EventSourcing\Util\Time\Clock\Native\NativeClock

  gember.event_sourcing_symfony_bundle.listener.initialize_use_case_attribute_registry_listener:
    class: Gember\EventSourcingSymfonyBundle\Listener\InitializeUseCaseAttributeRegistryListener
    tags: ['kernel.event_subscriber']
    arguments:
      - '@gember.event_sourcing.resolver.use_case.domain_tag_properties.domain_tag_properties_resolver'
      - '@gember.event_sourcing.resolver.use_case.subscriber_method_for_event.subscriber_method_for_event_resolver'
