services:
  _defaults:
    public: false

  gember.event_sourcing.event_store.event_store:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsEventStore
    arguments:
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_domain_event_envelope_factory'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_event_factory'
      - '@gember.event_sourcing.event_store.rdbms.rdbms_event_store_repository'

  gember.event_sourcing.event_store.domain_event_envelope_factory:
    class: Gember\EventSourcing\EventStore\DomainEventEnvelopeFactory
    arguments:
      - '@gember.event_sourcing.resolver.domain_event.domain_ids.domain_ids_resolver'
      - '@gember.event_sourcing.util.generator.identity.identity_generator'
      - '@gember.event_sourcing.util.time.clock.clock'

  gember.event_sourcing.event_store.rdbms.rdbms_domain_event_envelope_factory:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsDomainEventEnvelopeFactory
    arguments:
      - '@gember.event_sourcing.util.serialization.serializer.serializer'
      - '@gember.event_sourcing.registry.event_registry'

  gember.event_sourcing.event_store.rdbms.rdbms_event_factory:
    class: Gember\EventSourcing\EventStore\Rdbms\RdbmsEventFactory
    arguments:
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'
      - '@gember.event_sourcing.util.serialization.serializer.serializer'

  gember.event_sourcing.event_store.rdbms.rdbms_event_store_repository:
    class: Gember\RdbmsEventStoreDoctrineDbal\DoctrineDbalRdbmsEventStoreRepository
    arguments:
      - '@gember.doctrine.dbal.connection'
      - '@gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_table_schema'
      - '@gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_relation_table_schema'
      - '@gember.rdbms_event_store_doctrine_dbal.doctrine_dbal_rdbms_event_factory'

  gember.doctrine.dbal.connection: '@doctrine.dbal.default_connection'

  gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_table_schema:
    class: Gember\RdbmsEventStoreDoctrineDbal\TableSchema\EventStoreTableSchema
    factory: [
      Gember\RdbmsEventStoreDoctrineDbal\TableSchema\TableSchemaFactory,
      'createDefaultEventStore'
    ]

  gember.rdbms_event_store_doctrine_dbal.table_schema.event_store_relation_table_schema:
    class: Gember\RdbmsEventStoreDoctrineDbal\TableSchema\EventStoreRelationTableSchema
    factory: [
      Gember\RdbmsEventStoreDoctrineDbal\TableSchema\TableSchemaFactory,
      'createDefaultEventStoreRelation'
    ]

  gember.rdbms_event_store_doctrine_dbal.doctrine_dbal_rdbms_event_factory:
    class: Gember\RdbmsEventStoreDoctrineDbal\DoctrineDbalRdbmsEventFactory

  gember.event_sourcing.registry.event_registry:
    class: Gember\EventSourcing\Registry\Reflector\ReflectorEventRegistry
    arguments:
      - '@gember.event_sourcing.util.file.finder.finder'
      - '@gember.event_sourcing.util.file.reflector.reflector'
      - '@gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver'

  gember.event_sourcing.registry.cached.cached_event_registry_decorator:
    class: Gember\EventSourcing\Registry\Cached\CachedEventRegistryDecorator
    #decorates: gember.event_sourcing.registry.event_registry
    arguments:
      - '@.inner'
      - '@gember.event_sourcing.util.cache.cache'

  gember.event_sourcing.repository.domain_context_repository:
    class: Gember\EventSourcing\Repository\EventSourced\EventSourcedDomainContextRepository
    arguments:
      - '@gember.event_sourcing.event_store.event_store'
      - '@gember.event_sourcing.event_store.domain_event_envelope_factory'
      - '@gember.event_sourcing.resolver.domain_context.subscribed_events.subscribed_events_resolver'
      - '@gember.event_sourcing.util.messaging.message_bus.event_bus'

  Gember\EventSourcing\Repository\DomainContextRepository: '@gember.event_sourcing.repository.domain_context_repository'

  gember.event_sourcing.resolver.domain_context.domain_id_properties.domain_id_properties_resolver:
    class: Gember\EventSourcing\Resolver\DomainContext\DomainIdProperties\Attribute\AttributeDomainIdPropertiesResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_context.subscribed_events.subscribed_events_resolver:
    class: Gember\EventSourcing\Resolver\DomainContext\SubscribedEvents\Attribute\AttributeSubscribedEventsResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_context.subscriber_method_for_event.subscriber_method_for_event_resolver:
    class: Gember\EventSourcing\Resolver\DomainContext\SubscriberMethodForEvent\Attribute\AttributeSubscriberMethodForEventResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_event.domain_ids.domain_ids_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\DomainIds\Stacked\StackedDomainIdsResolver
    arguments:
      - [
        '@gember.event_sourcing.resolver.domain_event.domain_ids.attribute.attribute_domain_ids_resolver',
        '@gember.event_sourcing.resolver.domain_event.domain_ids.interface.interface_domain_ids_resolver'
      ]

  gember.event_sourcing.resolver.domain_event.domain_ids.attribute.attribute_domain_ids_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\DomainIds\Attribute\AttributeDomainIdsResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_event.domain_ids.interface.interface_domain_ids_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\DomainIds\Interface\InterfaceDomainIdsResolver

  gember.event_sourcing.resolver.domain_event.normalized_event_name.normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Stacked\StackedNormalizedEventNameResolver
    arguments:
      - [
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.attribute.attribute_normalized_event_name_resolver',
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.interface.interface_normalized_event_name_resolver',
        '@gember.event_sourcing.resolver.domain_event.normalized_event_name.class_name.class_name_normalized_event_name_resolver'
      ]

  gember.event_sourcing.resolver.domain_event.normalized_event_name.attribute.attribute_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Attribute\AttributeNormalizedEventNameResolver
    arguments:
      - '@gember.event_sourcing.util.attribute.resolver.attribute_resolver'

  gember.event_sourcing.resolver.domain_event.normalized_event_name.interface.interface_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\Interface\InterfaceNormalizedEventNameResolver

  gember.event_sourcing.resolver.domain_event.normalized_event_name.class_name.class_name_normalized_event_name_resolver:
    class: Gember\EventSourcing\Resolver\DomainEvent\NormalizedEventName\ClassName\ClassNameNormalizedEventNameResolver
    arguments:
      - '@gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer'

  gember.event_sourcing.util.attribute.resolver.attribute_resolver:
    class: Gember\EventSourcing\Util\Attribute\Resolver\Reflector\ReflectorAttributeResolver

  gember.event_sourcing.util.resolver.cached.cached_attribute_resolver_decorator:
    class: Gember\EventSourcing\Util\Attribute\Resolver\Cached\CachedAttributeResolverDecorator
    #decorates: gember.event_sourcing.util.attribute.resolver.attribute_resolver
    arguments:
      - '@.inner'
      - '@gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer'
      - '@gember.event_sourcing.util.cache.cache'

  gember.event_sourcing.util.cache.cache:
    class: Gember\CachePsr\PsrSimpleCache
    arguments:
      - '@gember.psr.simple_cache.cache_interface'

  gember.psr.simple_cache.cache_interface: '@gember.symfony.component.cache.psr16_cache'

  gember.symfony.component.cache.psr16_cache:
    class: Symfony\Component\Cache\Psr16Cache
    arguments:
      - '@gember.psr.cache.cache_item_pool_interface'

  gember.psr.cache.cache_item_pool_interface: ~

  gember.event_sourcing.util.file.finder.finder:
    class: Gember\FileFinderSymfony\SymfonyFinder
    arguments:
      - '@gember.file_finder_symfony.symfony_finder_factory'

  gember.file_finder_symfony.symfony_finder_factory:
    class: Gember\FileFinderSymfony\SymfonyFinderFactory

  gember.event_sourcing.util.file.reflector.reflector:
    class: Gember\FileReflectorRoave\RoaveBetterReflectionReflector
    arguments:
      - '@gember.file_reflector_roave.roave_better_reflection_factory'

  gember.file_reflector_roave.roave_better_reflection_factory:
    class: Gember\FileReflectorRoave\RoaveBetterReflectionFactory

  gember.event_sourcing.util.generator.identity.identity_generator: '@gember.identity_generator_symfony.uuid.symfony_uuid_identity_generator'

  Gember\EventSourcing\Util\Generator\Identity\IdentityGenerator: '@gember.event_sourcing.util.generator.identity.identity_generator'

  gember.identity_generator_symfony.uuid.symfony_uuid_identity_generator:
    class: Gember\IdentityGeneratorSymfony\Uuid\SymfonyUuidIdentityGenerator
    arguments:
      - '@Symfony\Component\Uid\Factory\UuidFactory'

  gember.identity_generator_symfony.ulid.symfony_ulid_identity_generator:
    class: Gember\IdentityGeneratorSymfony\Ulid\SymfonyUlidIdentityGenerator
    arguments:
      - '@Symfony\Component\Uid\Factory\UlidFactory'

  gember.event_sourcing.util.messaging.message_bus.event_bus:
    class: Gember\MessageBusSymfony\SymfonyEventBus
    arguments:
      - '@gember.symfony.component.messenger.message_bus.event_bus'

  gember.symfony.component.messenger.message_bus.event_bus: '@event.bus'

  gember.event_sourcing.util.serialization.serializer.serializer:
    class: Gember\EventSourcing\Util\Serialization\Serializer\Stacked\StackedSerializer
    arguments:
      - [
        '@gember.event_sourcing.util.serialization.serializer.serializable_domain_event.serializable_domain_event_serializer',
        '@gember.serializer_symfony.symfony_serializer'
      ]

  gember.event_sourcing.util.serialization.serializer.serializable_domain_event.serializable_domain_event_serializer:
    class: Gember\EventSourcing\Util\Serialization\Serializer\SerializableDomainEvent\SerializableDomainEventSerializer

  gember.serializer_symfony.symfony_serializer:
    class: Gember\SerializerSymfony\SymfonySerializer
    arguments:
      - '@gember.symfony.component.serializer.serializer_interface'

  gember.symfony.component.serializer.serializer_interface: '@serializer'

  gember.event_sourcing.util.string.friendly_class_namer.friendly_class_namer:
    class: Gember\EventSourcing\Util\String\FriendlyClassNamer\Native\NativeFriendlyClassNamer
    arguments:
      - '@gember.event_sourcing.util.string.inflector.inflector'

  gember.event_sourcing.util.string.inflector.inflector:
    class: Gember\EventSourcing\Util\String\Inflector\Native\NativeInflector

  gember.event_sourcing.util.time.clock.clock:
    class: Gember\EventSourcing\Util\Time\Clock\Native\NativeClock

  gember.event_sourcing_symfony_bundle.listener.initialize_domain_context_attribute_registry_listener:
    class: Gember\EventSourcingSymfonyBundle\Listener\InitializeDomainContextAttributeRegistryListener
    tags: ['kernel.event_subscriber']
    arguments:
      - '@gember.event_sourcing.resolver.domain_context.domain_id_properties.domain_id_properties_resolver'
      - '@gember.event_sourcing.resolver.domain_context.subscriber_method_for_event.subscriber_method_for_event_resolver'
